name: Deploy Application

on:
  branches:
    - master

jobs:
  create-deploy-artifacts:
    name: Create Deployment Arifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile Css and JavaScript

        run:
          npm install
          npm run prod
