name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  create-deploy-artifacts:
    name: Create Deployment Arifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile Css and JavaScript

        run:
          npm install
          npm run prod

      - name: Configure PHP 8.1
      - uses: shivammathur/setup-php@master
      - with:
          php-version: 8.1

          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer
